name: Claude

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  discussion:
    types: [created]
  discussion_comment:
    types: [created]

jobs:
  claude-code-action:
    # Only respond to @claude mentions from authorized users
    if: |
      (
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
        (github.event_name == 'issues' && contains(github.event.issue.body, '@claude')) ||
        (github.event_name == 'discussion' && contains(github.event.discussion.body, '@claude')) ||
        (github.event_name == 'discussion_comment' && contains(github.event.comment.body, '@claude'))
      ) && (
        github.actor == 'zbeyens' ||
        github.actor == 'felixfeng33'
      )
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      discussions: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude PR Action
        uses: grll/claude-code-action@beta
        with:
          use_oauth: true
          claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          timeout_minutes: '60'
